
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "COLOR COMMENT END_PRINT ID NEW_PRINT NUMBER PRINT_O PRINT_STAR PRINT_TRI PRINT_X\n    start   : prints\n    \n    prints  : prints NEW_PRINT ID ';' statements END_PRINT ';'\n            | NEW_PRINT ID ';' statements END_PRINT ';'\n    \n    statements  : statements statement ';'\n                | statement ';'\n    \n    statement   :\n                |   PRINT_X '(' NUMBER ',' NUMBER ',' COLOR ')'\n                |   PRINT_O '(' NUMBER ',' NUMBER ',' COLOR ')'\n                |   PRINT_TRI '(' NUMBER ',' NUMBER ',' COLOR ')'\n                |   PRINT_STAR '(' NUMBER ',' NUMBER ',' COLOR ')'\n    "
    
_lr_action_items = {'NEW_PRINT':([0,2,24,30,],[3,4,-3,-2,]),'$end':([1,2,24,30,],[0,-1,-3,-2,]),'ID':([3,4,],[5,6,]),';':([5,6,7,8,9,10,15,16,17,18,23,25,47,48,49,50,],[7,8,-6,-6,-6,18,-6,24,25,-5,30,-4,-7,-8,-9,-10,]),'PRINT_X':([7,8,9,15,18,25,],[11,11,11,11,-5,-4,]),'PRINT_O':([7,8,9,15,18,25,],[12,12,12,12,-5,-4,]),'PRINT_TRI':([7,8,9,15,18,25,],[13,13,13,13,-5,-4,]),'PRINT_STAR':([7,8,9,15,18,25,],[14,14,14,14,-5,-4,]),'END_PRINT':([9,15,18,25,],[16,23,-5,-4,]),'(':([11,12,13,14,],[19,20,21,22,]),'NUMBER':([19,20,21,22,31,32,33,34,],[26,27,28,29,35,36,37,38,]),',':([26,27,28,29,35,36,37,38,],[31,32,33,34,39,40,41,42,]),'COLOR':([39,40,41,42,],[43,44,45,46,]),')':([43,44,45,46,],[47,48,49,50,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'prints':([0,],[2,]),'statements':([7,8,],[9,15,]),'statement':([7,8,9,15,],[10,10,17,17,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> prints','start',1,'p_star','parser.py',13),
  ('prints -> prints NEW_PRINT ID ; statements END_PRINT ;','prints',7,'p_prints','parser.py',20),
  ('prints -> NEW_PRINT ID ; statements END_PRINT ;','prints',6,'p_prints','parser.py',21),
  ('statements -> statements statement ;','statements',3,'p_statements_sequence','parser.py',31),
  ('statements -> statement ;','statements',2,'p_statements_sequence','parser.py',32),
  ('statement -> <empty>','statement',0,'p_statement_definition','parser.py',42),
  ('statement -> PRINT_X ( NUMBER , NUMBER , COLOR )','statement',8,'p_statement_definition','parser.py',43),
  ('statement -> PRINT_O ( NUMBER , NUMBER , COLOR )','statement',8,'p_statement_definition','parser.py',44),
  ('statement -> PRINT_TRI ( NUMBER , NUMBER , COLOR )','statement',8,'p_statement_definition','parser.py',45),
  ('statement -> PRINT_STAR ( NUMBER , NUMBER , COLOR )','statement',8,'p_statement_definition','parser.py',46),
]
