
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "COLOR COMMENT END_PRINT ID NEW_PRINT NUMBER PRINT_O PRINT_STAR PRINT_TRI PRINT_X\n    start   : prints\n    \n    prints  : prints print\n            | print\n    \n    print   : NEW_PRINT ID ';' statements END_PRINT ';'\n    \n    statements  : statements statement ';'\n                | statement ';'\n    \n    statement   :\n                |   PRINT_X '(' NUMBER ',' NUMBER ',' COLOR ')'\n                |   PRINT_O '(' NUMBER ',' NUMBER ',' COLOR ')'\n                |   PRINT_TRI '(' NUMBER ',' NUMBER ',' COLOR ')'\n                |   PRINT_STAR '(' NUMBER ',' NUMBER ',' COLOR ')'\n    "
    
_lr_action_items = {'NEW_PRINT':([0,2,3,5,21,],[4,4,-3,-2,-4,]),'$end':([1,2,3,5,21,],[0,-1,-3,-2,-4,]),'ID':([4,],[6,]),';':([6,7,8,9,14,15,16,22,43,44,45,46,],[7,-7,-7,16,21,22,-6,-5,-8,-9,-10,-11,]),'PRINT_X':([7,8,16,22,],[10,10,-6,-5,]),'PRINT_O':([7,8,16,22,],[11,11,-6,-5,]),'PRINT_TRI':([7,8,16,22,],[12,12,-6,-5,]),'PRINT_STAR':([7,8,16,22,],[13,13,-6,-5,]),'END_PRINT':([8,16,22,],[14,-6,-5,]),'(':([10,11,12,13,],[17,18,19,20,]),'NUMBER':([17,18,19,20,27,28,29,30,],[23,24,25,26,31,32,33,34,]),',':([23,24,25,26,31,32,33,34,],[27,28,29,30,35,36,37,38,]),'COLOR':([35,36,37,38,],[39,40,41,42,]),')':([39,40,41,42,],[43,44,45,46,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'prints':([0,],[2,]),'print':([0,2,],[3,5,]),'statements':([7,],[8,]),'statement':([7,8,],[9,15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> prints','start',1,'p_star','parser.py',13),
  ('prints -> prints print','prints',2,'p_prints','parser.py',20),
  ('prints -> print','prints',1,'p_prints','parser.py',21),
  ('print -> NEW_PRINT ID ; statements END_PRINT ;','print',6,'p_print','parser.py',31),
  ('statements -> statements statement ;','statements',3,'p_statements_sequence','parser.py',38),
  ('statements -> statement ;','statements',2,'p_statements_sequence','parser.py',39),
  ('statement -> <empty>','statement',0,'p_statement_definition','parser.py',49),
  ('statement -> PRINT_X ( NUMBER , NUMBER , COLOR )','statement',8,'p_statement_definition','parser.py',50),
  ('statement -> PRINT_O ( NUMBER , NUMBER , COLOR )','statement',8,'p_statement_definition','parser.py',51),
  ('statement -> PRINT_TRI ( NUMBER , NUMBER , COLOR )','statement',8,'p_statement_definition','parser.py',52),
  ('statement -> PRINT_STAR ( NUMBER , NUMBER , COLOR )','statement',8,'p_statement_definition','parser.py',53),
]
